# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Bolove.BoMirror
PackageVersion: 1.4.3
InstallerLocale: tr-TR
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: '{6B1D0C8E-4E2B-4C3B-9B8E-3F0A6C5D2E71}_is1'
AppsAndFeaturesEntries:
- DisplayName: BoMirror
  Publisher: Bolove
  DisplayVersion: 1.4.3
  ProductCode: '{6B1D0C8E-4E2B-4C3B-9B8E-3F0A6C5D2E71}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://bolove.tr/bomirror/?f=kurulum&v=1.4.3
  InstallerSha256: 1EA30983851CD25DBFB156189C50397F70E8FB577F34EAB43612AC757D0400D2
ManifestType: installer
ManifestVersion: 1.9.0
